Thu Aug 25 14:10:34 -0400 2011
SIGTERM
["/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:46:in `sleep'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:46:in `watch'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:45:in `each'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:45:in `watch'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:44:in `loop'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:44:in `watch'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:84:in `start_with_pidfile'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:64:in `fork'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:64:in `start_with_pidfile'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:111:in `start'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/application_group.rb:149:in `create_monitor'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/application.rb:282:in `start'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/controller.rb:70:in `run'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons.rb:145:in `run'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/cmdline.rb:109:in `call'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/cmdline.rb:109:in `catch_exceptions'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons.rb:144:in `run'", "/Users/cmmagid/rails_projects/Webiva/script/workling_client:17"]
Fri Aug 26 11:59:26 -0400 2011
SIGTERM
["/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:57:in `sleep'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:57:in `watch'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:44:in `loop'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:44:in `watch'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:84:in `start_with_pidfile'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:64:in `fork'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:64:in `start_with_pidfile'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:111:in `start'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/application_group.rb:149:in `create_monitor'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/application.rb:282:in `start'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/controller.rb:70:in `run'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons.rb:145:in `run'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/cmdline.rb:109:in `call'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/cmdline.rb:109:in `catch_exceptions'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons.rb:144:in `run'", "/Users/cmmagid/rails_projects/Webiva/script/workling_client:17"]
Fri Aug 26 11:59:27 -0400 2011
SIGTERM
["/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:57:in `sleep'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:57:in `watch'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:44:in `loop'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:44:in `watch'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:84:in `start_with_pidfile'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:64:in `fork'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:64:in `start_with_pidfile'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:111:in `start'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/application_group.rb:149:in `create_monitor'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/application.rb:282:in `start'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/controller.rb:70:in `run'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons.rb:145:in `run'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/cmdline.rb:109:in `call'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/cmdline.rb:109:in `catch_exceptions'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons.rb:144:in `run'", "/Users/cmmagid/rails_projects/Webiva/script/workling_client:17"]
Fri Aug 26 18:37:53 -0400 2011
SIGTERM
["/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:46:in `sleep'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:46:in `watch'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:45:in `each'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:45:in `watch'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:44:in `loop'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:44:in `watch'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:84:in `start_with_pidfile'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:64:in `fork'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:64:in `start_with_pidfile'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:111:in `start'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/application_group.rb:149:in `create_monitor'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/application.rb:282:in `start'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/controller.rb:70:in `run'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons.rb:145:in `run'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/cmdline.rb:109:in `call'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/cmdline.rb:109:in `catch_exceptions'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons.rb:144:in `run'", "/Users/cmmagid/rails_projects/Webiva/script/workling_client:17"]
Wed Aug 31 18:22:41 -0400 2011
SIGTERM
["/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:57:in `sleep'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:57:in `watch'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:44:in `loop'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:44:in `watch'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:84:in `start_with_pidfile'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:64:in `fork'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:64:in `start_with_pidfile'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:111:in `start'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/application_group.rb:149:in `create_monitor'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/application.rb:282:in `start'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/controller.rb:70:in `run'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons.rb:145:in `run'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/cmdline.rb:109:in `call'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/cmdline.rb:109:in `catch_exceptions'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons.rb:144:in `run'", "/Users/cmmagid/rails_projects/Webiva/script/workling_client:17"]
Fri Sep 02 19:47:18 -0400 2011
SIGTERM
["/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:57:in `sleep'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:57:in `watch'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:44:in `loop'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:44:in `watch'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:84:in `start_with_pidfile'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:64:in `fork'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:64:in `start_with_pidfile'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:111:in `start'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/application_group.rb:149:in `create_monitor'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/application.rb:282:in `start'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/controller.rb:70:in `run'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons.rb:145:in `run'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/cmdline.rb:109:in `call'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/cmdline.rb:109:in `catch_exceptions'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons.rb:144:in `run'", "/Users/cmmagid/rails_projects/Webiva/script/workling_client:17"]
*** below you find the most recent exception thrown, this will be likely (but not certainly) the exception that made the application exit abnormally ***
#<MissingSourceFile: no such file to load -- eventmachine>
*** below you find all exception objects found in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
#<NoMemoryError: failed to allocate memory>
#<SystemStackError: stack level too deep>
#<fatal: exception reentered>
#<LoadError: no such file to load -- daemons>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<MissingSourceFile: no such file to load -- eventmachine>
*** below you find the most recent exception thrown, this will be likely (but not certainly) the exception that made the application exit abnormally ***
#<Errno::EAGAIN: Resource temporarily unavailable>
*** below you find all exception objects found in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
#<NoMemoryError: failed to allocate memory>
#<SystemStackError: stack level too deep>
#<fatal: exception reentered>
#<LoadError: no such file to load -- daemons>
#<MissingSourceFile: no such file to load -- eventmachine>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
*** below you find the most recent exception thrown, this will be likely (but not certainly) the exception that made the application exit abnormally ***
#<Errno::EAGAIN: Resource temporarily unavailable>
*** below you find all exception objects found in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
#<NoMemoryError: failed to allocate memory>
#<SystemStackError: stack level too deep>
#<fatal: exception reentered>
#<LoadError: no such file to load -- daemons>
#<MissingSourceFile: no such file to load -- eventmachine>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
Tue Sep 06 14:18:20 -0400 2011
SIGTERM
["/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:57:in `sleep'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:57:in `watch'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:44:in `loop'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:44:in `watch'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:84:in `start_with_pidfile'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:64:in `fork'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:64:in `start_with_pidfile'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:111:in `start'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/application_group.rb:149:in `create_monitor'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/application.rb:282:in `start'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/controller.rb:70:in `run'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons.rb:145:in `run'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/cmdline.rb:109:in `call'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/cmdline.rb:109:in `catch_exceptions'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons.rb:144:in `run'", "/Users/cmmagid/rails_projects/Webiva/script/workling_client:17"]
Fri Sep 09 18:09:30 -0400 2011
SIGTERM
["/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:57:in `sleep'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:57:in `watch'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:44:in `loop'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:44:in `watch'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:84:in `start_with_pidfile'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:64:in `fork'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:64:in `start_with_pidfile'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:111:in `start'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/application_group.rb:149:in `create_monitor'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/application.rb:282:in `start'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/controller.rb:70:in `run'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons.rb:145:in `run'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/cmdline.rb:109:in `call'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/cmdline.rb:109:in `catch_exceptions'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons.rb:144:in `run'", "/Users/cmmagid/rails_projects/Webiva/script/workling_client:17"]
*** below you find the most recent exception thrown, this will be likely (but not certainly) the exception that made the application exit abnormally ***
#<MissingSourceFile: no such file to load -- eventmachine>
*** below you find all exception objects found in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
#<NoMemoryError: failed to allocate memory>
#<SystemStackError: stack level too deep>
#<fatal: exception reentered>
#<LoadError: no such file to load -- daemons>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<MissingSourceFile: no such file to load -- eventmachine>
*** below you find the most recent exception thrown, this will be likely (but not certainly) the exception that made the application exit abnormally ***
#<Errno::EAGAIN: Resource temporarily unavailable>
*** below you find all exception objects found in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
#<NoMemoryError: failed to allocate memory>
#<SystemStackError: stack level too deep>
#<fatal: exception reentered>
#<LoadError: no such file to load -- daemons>
#<MissingSourceFile: no such file to load -- eventmachine>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
*** below you find the most recent exception thrown, this will be likely (but not certainly) the exception that made the application exit abnormally ***
#<Errno::EAGAIN: Resource temporarily unavailable>
*** below you find all exception objects found in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
#<NoMemoryError: failed to allocate memory>
#<SystemStackError: stack level too deep>
#<fatal: exception reentered>
#<LoadError: no such file to load -- daemons>
#<MissingSourceFile: no such file to load -- eventmachine>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
*** below you find the most recent exception thrown, this will be likely (but not certainly) the exception that made the application exit abnormally ***
#<Errno::EAGAIN: Resource temporarily unavailable>
*** below you find all exception objects found in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
#<NoMemoryError: failed to allocate memory>
#<SystemStackError: stack level too deep>
#<fatal: exception reentered>
#<LoadError: no such file to load -- daemons>
#<MissingSourceFile: no such file to load -- eventmachine>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
*** below you find the most recent exception thrown, this will be likely (but not certainly) the exception that made the application exit abnormally ***
#<Errno::EAGAIN: Resource temporarily unavailable>
*** below you find all exception objects found in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
#<NoMemoryError: failed to allocate memory>
#<SystemStackError: stack level too deep>
#<fatal: exception reentered>
#<LoadError: no such file to load -- daemons>
#<MissingSourceFile: no such file to load -- eventmachine>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
*** below you find the most recent exception thrown, this will be likely (but not certainly) the exception that made the application exit abnormally ***
#<Errno::EAGAIN: Resource temporarily unavailable>
*** below you find all exception objects found in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
#<NoMemoryError: failed to allocate memory>
#<SystemStackError: stack level too deep>
#<fatal: exception reentered>
#<LoadError: no such file to load -- daemons>
#<MissingSourceFile: no such file to load -- eventmachine>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
*** below you find the most recent exception thrown, this will be likely (but not certainly) the exception that made the application exit abnormally ***
#<Errno::EAGAIN: Resource temporarily unavailable>
*** below you find all exception objects found in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
#<NoMemoryError: failed to allocate memory>
#<SystemStackError: stack level too deep>
#<fatal: exception reentered>
#<LoadError: no such file to load -- daemons>
#<MissingSourceFile: no such file to load -- eventmachine>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
*** below you find the most recent exception thrown, this will be likely (but not certainly) the exception that made the application exit abnormally ***
#<Errno::EAGAIN: Resource temporarily unavailable>
*** below you find all exception objects found in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
#<NoMemoryError: failed to allocate memory>
#<SystemStackError: stack level too deep>
#<fatal: exception reentered>
#<LoadError: no such file to load -- daemons>
#<MissingSourceFile: no such file to load -- eventmachine>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
*** below you find the most recent exception thrown, this will be likely (but not certainly) the exception that made the application exit abnormally ***
#<Errno::EAGAIN: Resource temporarily unavailable>
*** below you find all exception objects found in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
#<NoMemoryError: failed to allocate memory>
#<SystemStackError: stack level too deep>
#<fatal: exception reentered>
#<LoadError: no such file to load -- daemons>
#<MissingSourceFile: no such file to load -- eventmachine>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
*** below you find the most recent exception thrown, this will be likely (but not certainly) the exception that made the application exit abnormally ***
#<Errno::EAGAIN: Resource temporarily unavailable>
*** below you find all exception objects found in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
#<NoMemoryError: failed to allocate memory>
#<SystemStackError: stack level too deep>
#<fatal: exception reentered>
#<LoadError: no such file to load -- daemons>
#<MissingSourceFile: no such file to load -- eventmachine>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
*** below you find the most recent exception thrown, this will be likely (but not certainly) the exception that made the application exit abnormally ***
#<Errno::EAGAIN: Resource temporarily unavailable>
*** below you find all exception objects found in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
#<NoMemoryError: failed to allocate memory>
#<SystemStackError: stack level too deep>
#<fatal: exception reentered>
#<LoadError: no such file to load -- daemons>
#<MissingSourceFile: no such file to load -- eventmachine>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
*** below you find the most recent exception thrown, this will be likely (but not certainly) the exception that made the application exit abnormally ***
#<Errno::EAGAIN: Resource temporarily unavailable>
*** below you find all exception objects found in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
#<NoMemoryError: failed to allocate memory>
#<SystemStackError: stack level too deep>
#<fatal: exception reentered>
#<LoadError: no such file to load -- daemons>
#<MissingSourceFile: no such file to load -- eventmachine>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
*** below you find the most recent exception thrown, this will be likely (but not certainly) the exception that made the application exit abnormally ***
#<Errno::EAGAIN: Resource temporarily unavailable>
*** below you find all exception objects found in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
#<NoMemoryError: failed to allocate memory>
#<SystemStackError: stack level too deep>
#<fatal: exception reentered>
#<LoadError: no such file to load -- daemons>
#<MissingSourceFile: no such file to load -- eventmachine>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
